### ISSUE TITLE
ImportError: cannot import name 'cpp_household' on Arch Linux

### ISSUE THREAD

**Issue by trougnouf** [openai/roboschool#138]
Hello all,
I made a package on Arch Linux, https://aur.archlinux.org/packages/roboschool-git/ , the list of steps used for building are located on https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=roboschool-git .
I managed to get the build and installation to complete with a small change in the cpp-household makefile (removing BOOST_PYTHON3_POSTFIX) from the linker, and everything else is mostly the same (with python-setuptools being used instead of pip, for the same result I believe). However, I get the following when I try to import the library:

```$ python
Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import roboschool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/roboschool/__init__.py", line 105, in <module>
    from roboschool.gym_pendulums import RoboschoolInvertedPendulum
  File "/usr/lib/python3.6/site-packages/roboschool/gym_pendulums.py", line 1, in <module>
    from roboschool.scene_abstract import SingleRobotEmptyScene
  File "/usr/lib/python3.6/site-packages/roboschool/scene_abstract.py", line 12, in <module>
    from roboschool  import cpp_household   as cpp_household
ImportError: cannot import name 'cpp_household'
>>> 
```
I noticed that cpp_household.so is present in src/roboschool/roboschool/cpp_household.so but not in the final package (which I've attached). I don't know if that's related. I tried copying it to /usr/lib and /usr/lib/python3.6/site-packages/roboschool/cpp-household/bullet_local_install/lib (where I saw other *.so files) but that didn't help. I don't know what else to try from here.

[roboschool-git-r242.675f1ac4-1-any.pkg.zip](https://github.com/openai/roboschool/files/1993666/roboschool-git-r242.675f1ac4-1-any.pkg.zip)

**Comment by trougnouf** [comment]
I solved the previous error by copying cpp_household.so from the source directory to /usr/lib/python3.6/site-packages/roboschool/ 
I currently get the following:
```
$ python
Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import roboschool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/roboschool/__init__.py", line 105, in <module>
    from roboschool.gym_pendulums import RoboschoolInvertedPendulum
  File "/usr/lib/python3.6/site-packages/roboschool/gym_pendulums.py", line 1, in <module>
    from roboschool.scene_abstract import SingleRobotEmptyScene
  File "/usr/lib/python3.6/site-packages/roboschool/scene_abstract.py", line 12, in <module>
    from roboschool  import cpp_household   as cpp_household
ImportError: /usr/lib/libboost_python.so.1.66.0: undefined symbol: PyString_InternFromString
>>> 
```

**Comment by trougnouf** [comment]
That last one was due to not adding a 3 in the Makefile modification, ```sed -i -e s/\$\(BOOST_PYTHON3_POSTFIX\)/3/g Makefile``` did the trick :)
