### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by rnunziata** [openai/roboschool#161]
import robotschool:
```

rjn@rjn-Oryx-Pro:~/roboschool$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import roboschool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rjn/roboschool/roboschool/__init__.py", line 9, in <module>
    tags={ "pg_complexity": 1*1000000 },
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_episode_steps'




```

**Comment by rnunziata** [comment]
resolved: upgraded gym
