### ISSUE TITLE
version incompatability

### ISSUE THREAD

**Issue by rnunziata** [openai/roboschool#162]
Some kind of version incompatibility can you list all versions dependencies. for universe and gym 

```
rjn@rjn-Oryx-Pro:~/roboschool$ python3 $ROBOSCHOOL_PATH/agent_zoo/RoboschoolHumanoidFlagrun_v0_2017may.py
Traceback (most recent call last):
  File "/home/rjn/roboschool/agent_zoo/RoboschoolHumanoidFlagrun_v0_2017may.py", line 1, in <module>
    import gym, roboschool
  File "/home/rjn/roboschool/roboschool/__init__.py", line 9, in <module>
    tags={ "pg_complexity": 1*1000000 },
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 124, in register
    return registry.register(id, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 118, in register
    self.env_specs[id] = EnvSpec(id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'max_episode_steps'

```

Name: universe
Version: 0.21.3

Name: gym
Version: 0.7.0

**Comment by rnunziata** [comment]
resloved

gym<0.8,>=0.7 in /usr/local/lib/python3.5/dist-packages (from universe) (0.7.4)
 universe          in /home/rjn/.local/lib/python3.5/site-packages (0.21.3)
