### ISSUE TITLE
Import error with initcpp_household

### ISSUE THREAD

**Issue by phansel** [openai/roboschool#20]
System details:
Ubuntu 17.04 
Asrock AB350M Pro4 motherboard, Ryzen 5
NVIDIA GTX 1060 GPU

I was able to install Roboschool and add it to my PYTHONPATH variable in .bashrc, but this ImportError remains.

`paul@desktop:/home$ python $ROBOSCHOOL_PATH/agent_zoo/demo_race2.py
Traceback (most recent call last):
  File "/media/code/roboschool/agent_zoo/demo_race2.py", line 1, in <module>
    import gym, roboschool
  File "/media/code/roboschool/roboschool/__init__.py", line 80, in <module>
    from roboschool.gym_pendulums import RoboschoolInvertedPendulum
  File "/media/code/roboschool/roboschool/gym_pendulums.py", line 1, in <module>
    from roboschool.scene_abstract import SingleRobotEmptyScene
  File "/media/code/roboschool/roboschool/scene_abstract.py", line 5, in <module>
    from roboschool  import cpp_household   as cpp_household
ImportError: dynamic module does not define init function (initcpp_household)
`

**Comment by phansel** [comment]
Solved the issue: gym was not defined in the PYTHONPATH, and numpy was not installed for python3.
