### ISSUE TITLE
Traceback (most recent call last):   File "<stdin>", line 1, in <module>   File "/home/svu/biehz/zhimin/software/roboschool_lib/roboschool/__init__.py", line 112, in <module>     from roboschool.gym_pendulums import RoboschoolInvertedPendulum   File "/home/svu/biehz/zhimin/software/roboschool_lib/roboschool/gym_pendulums.py", line 1, in <module>     from roboschool.scene_abstract import SingleRobotEmptyScene   File "/home/svu/biehz/zhimin/software/roboschool_lib/roboschool/scene_abstract.py", line 12, in <module>     from roboschool  import cpp_household   as cpp_household ImportError: cannot import name 'cpp_household' >>> 

### ISSUE THREAD

**Issue by hzm2016** [openai/roboschool#203]

**Comment by deperado007** [comment]
how to solve it?
